### ISSUE TITLE
Can not be used in tensorflow 1.0

### ISSUE THREAD

**Issue by mrvgao** [GradySimon/tf-glove#3]
Hi, this project has several lines which cannot run in tensorflow 1.0. And in my project, I have fixed it. Can I merge these updates? 

Thanks.

**Comment by GradySimon** [comment]
Sure! And thanks! Were you going to submit a pull request?

**Comment by mrvgao** [comment]
I have pulled a request just before.  Thanks!

**Comment by GradySimon** [comment]
Thanks! Merged it in 1b8e665 along with a couple other TF 1.0 compatibility fixes.
